/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmangame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac Ogunleye
 */


public class Level3 extends javax.swing.JFrame {

    /**
     * Creates new form Level3
     */
    String val1, val2, val3, val4, val5, val6;
    int xOffset, yOffset;
    
    
    public Level3() {
        initComponents();

        setSize(760, 501);
        setVisible(true);

        setLocationRelativeTo(null);
        setResizable(false);
    }

    public void answer() {

        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        if (!item1.getText().equals("") && !item2.getText().equals("")
                && !item3.getText().equals("") && !item4.getText().equals("")
                && !item5.getText().equals("") && !item6.getText().equals("")) {

            if (!val1.equals("P") && !val2.equals("I") && !val3.equals("R") && !val4.equals("A")
                    && !val5.equals("T") && !val6.equals("E")) {
                JOptionPane.showMessageDialog(null, "Sucess!!", "Notice",
                        JOptionPane.INFORMATION_MESSAGE);
                nextbtn.setEnabled(true);

                jButton6.setEnabled(false);
                jButton8.setEnabled(false);
                jButton9.setEnabled(false);
                jButton10.setEnabled(false);

                item1.setEnabled(true);
                item1.setEditable(false);

                item2.setEnabled(true);
                item2.setEditable(false);

                item3.setEnabled(true);
                item3.setEditable(false);

                item4.setEnabled(true);
                item4.setEditable(false);

                item5.setEnabled(true);
                item5.setEditable(false);

                item6.setEnabled(true);
                item6.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Fail!!", "Notice",
                        JOptionPane.INFORMATION_MESSAGE);
                nextbtn.setEnabled(false);
            }
        } else {
                
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        item3 = new javax.swing.JTextField();
        item1 = new javax.swing.JTextField();
        item2 = new javax.swing.JTextField();
        item4 = new javax.swing.JTextField();
        item6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        item5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setMinimumSize(new java.awt.Dimension(760, 501));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        nextbtn.setBackground(new java.awt.Color(0, 0, 0));
        nextbtn.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        nextbtn.setForeground(new java.awt.Color(255, 255, 255));
        nextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Image/icons8_Arrow_48px.png"))); // NOI18N
        nextbtn.setText("NEXT");
        nextbtn.setToolTipText("Click to go to next level");
        nextbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 153), new java.awt.Color(255, 102, 153), null));
        nextbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextbtn.setEnabled(false);
        nextbtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nextbtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nextbtnStateChanged(evt);
            }
        });
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextbtn);
        nextbtn.setBounds(632, 383, 112, 69);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minimize_Window_48px.png"))); // NOI18N
        jLabel1.setToolTipText("Minimize");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(624, 4, 51, 45);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_48px.png"))); // NOI18N
        jLabel2.setToolTipText("Close");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(687, 4, 51, 45);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("T");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(474, 322, 60, 53);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("I");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(117, 322, 60, 53);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("E");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(204, 322, 60, 53);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("A");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(295, 322, 60, 53);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("S");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(383, 322, 60, 53);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("P");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(117, 389, 60, 53);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("B");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(204, 389, 60, 53);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("O");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(295, 389, 60, 53);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Y");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(383, 389, 60, 53);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("R");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(474, 389, 60, 53);

        item3.setEditable(false);
        item3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(item3);
        item3.setBounds(300, 200, 60, 49);

        item1.setEditable(false);
        item1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jPanel1.add(item1);
        item1.setBounds(120, 200, 60, 49);

        item2.setEditable(false);
        item2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });
        jPanel1.add(item2);
        item2.setBounds(210, 200, 60, 49);

        item4.setEditable(false);
        item4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });
        jPanel1.add(item4);
        item4.setBounds(390, 200, 60, 49);

        item6.setEditable(false);
        item6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(item6);
        item6.setBounds(550, 200, 60, 49);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/icons8_Idea_48px.png"))); // NOI18N
        jLabel3.setText("GUESS THE CORRCT WORD");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 10, 400, 60);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Image/icons8_Home_52px.png"))); // NOI18N
        jButton12.setText("MAIN MENU");
        jButton12.setToolTipText("click to go back to Game Main Menu");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(10, 10, 130, 80);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LEVEL 3");
        jLabel4.setToolTipText("Level 1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(630, 330, 110, 40);

        question.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("A Sea Thief is Called?");
        question.setToolTipText("question");
        jPanel1.add(question);
        question.setBounds(240, 100, 300, 60);

        item5.setEditable(false);
        item5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(item5);
        item5.setBounds(470, 200, 60, 49);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nextbtnStateChanged
        // TODO add your handling code here:
        //        isComplete1();
        //        if(isComplete1() == true){
        //            jButton1.setEnabled(true);
        //        }
    }//GEN-LAST:event_nextbtnStateChanged

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextbtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Do you wany to exit the Game?");
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);

            if (res == JOptionPane.NO_OPTION) {
                return;
            }

        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item5.setText("T");
        jButton2.setText("");
        if (jButton2.getText() == "") {
            jButton2.setEnabled(false);
        }

        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item2.setText("I");
        jButton3.setText("");
        if (jButton3.getText() == "") {
            jButton3.setEnabled(false);
        }
        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item6.setText("E");
        jButton4.setText("");
        if (jButton4.getText() == "") {
            jButton4.setEnabled(false);

        }
        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item4.setText("A");
        jButton5.setText("");
        if (jButton5.getText() == "") {
            jButton5.setEnabled(false);

        }

        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
                JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item1.setText("P");
        jButton7.setText("");
        if (jButton7.getText() == "") {
            jButton7.setEnabled(false);

        }

        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
                JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
                JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
                JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
                JOptionPane.INFORMATION_MESSAGE);

        item3.setText("R");

        jButton11.setText("");
        if (jButton11.getText() == "") {
            jButton11.setEnabled(false);
        }
        val1 = jButton3.getText();
        val2 = jButton9.getText();
        val3 = jButton9.getText();
        val4 = jButton2.getText();
        val5 = jButton6.getText();
        val6 = jButton4.getText();

        answer();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item2ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "the game is still ongoing\nDo you wany to return to the main menu?");
        if (res == JOptionPane.YES_OPTION) {
            HomePage home = new HomePage();
            dispose();

            if (res == JOptionPane.NO_OPTION) {
                return;
            }

        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xOffset = evt.getX();
        yOffset = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
         int Kox = evt.getXOnScreen();
           int koy = evt.getYOnScreen();
           
           this.setLocation(Kox - xOffset, koy - yOffset);
           
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField item1;
    private javax.swing.JTextField item2;
    private javax.swing.JTextField item3;
    private javax.swing.JTextField item4;
    private javax.swing.JTextField item5;
    private javax.swing.JTextField item6;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextbtn;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
