/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmangame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac Ogunleye
 */
public class LevelTwo extends javax.swing.JFrame {

    /**
     * Creates new form LevelTwo
     */
    String val1, val2, val3, val4, val5;
    int xOffset, yOffset;
    
    public LevelTwo() {
        initComponents();
        
        setSize(760, 501);
        setVisible(true);
        
         setLocationRelativeTo(null);
         setResizable(false);
    }
    
     public void answer(){
        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();
        
        if(!item1.getText().equals("") && !item2.getText().equals("")
              && !item3.getText().equals("")  && !item4.getText().equals("")
                 && !item5.getText().equals("")){
            
            if(!val1.equals("S") && !val2.equals("H") && !val3.equals("O") && !val4.equals("R")
                    && !val5.equals("T")){
                JOptionPane.showMessageDialog(null, "Sucess!!", "Notice",
                        JOptionPane.INFORMATION_MESSAGE);
                nextbtn.setEnabled(true);
                
        btnN.setEnabled(false);
        btnZ.setEnabled(false);
        btnG.setEnabled(false);
        btnU.setEnabled(false);
        btnJ.setEnabled(false);
        
        
        item1.setEnabled(true);
        item1.setEditable(false);
        
        item2.setEnabled(true);
        item2.setEditable(false);
        
        item3.setEnabled(true);
        item3.setEditable(false);
        
        item4.setEnabled(true);
        item4.setEditable(false);
        
        item5.setEnabled(true);
        item5.setEditable(false);
            }else{
                JOptionPane.showMessageDialog(null, "Fail!!", "Notice",
                        JOptionPane.ERROR_MESSAGE);
                nextbtn.setEnabled(false);
            }
        }else{
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnT = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        item3 = new javax.swing.JTextField();
        item1 = new javax.swing.JTextField();
        item2 = new javax.swing.JTextField();
        item4 = new javax.swing.JTextField();
        item5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setMinimumSize(new java.awt.Dimension(760, 501));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        nextbtn.setBackground(new java.awt.Color(0, 0, 0));
        nextbtn.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        nextbtn.setForeground(new java.awt.Color(255, 255, 255));
        nextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Image/icons8_Arrow_48px.png"))); // NOI18N
        nextbtn.setText("NEXT");
        nextbtn.setToolTipText("Click to go to next level");
        nextbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 153), new java.awt.Color(255, 102, 153), null));
        nextbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextbtn.setEnabled(false);
        nextbtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nextbtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nextbtnStateChanged(evt);
            }
        });
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextbtn);
        nextbtn.setBounds(632, 383, 112, 69);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minimize_Window_48px.png"))); // NOI18N
        jLabel1.setToolTipText("Minimize");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(624, 4, 51, 45);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_48px.png"))); // NOI18N
        jLabel2.setToolTipText("Close");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(687, 4, 51, 45);

        btnT.setBackground(new java.awt.Color(0, 0, 0));
        btnT.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnT.setForeground(new java.awt.Color(255, 255, 255));
        btnT.setText("T");
        btnT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });
        jPanel1.add(btnT);
        btnT.setBounds(474, 322, 60, 53);

        btnH.setBackground(new java.awt.Color(0, 0, 0));
        btnH.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnH.setForeground(new java.awt.Color(255, 255, 255));
        btnH.setText("H");
        btnH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        jPanel1.add(btnH);
        btnH.setBounds(117, 322, 60, 53);

        btnN.setBackground(new java.awt.Color(0, 0, 0));
        btnN.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnN.setForeground(new java.awt.Color(255, 255, 255));
        btnN.setText("N");
        btnN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        jPanel1.add(btnN);
        btnN.setBounds(204, 322, 60, 53);

        btnZ.setBackground(new java.awt.Color(0, 0, 0));
        btnZ.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnZ.setForeground(new java.awt.Color(255, 255, 255));
        btnZ.setText("Z");
        btnZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });
        jPanel1.add(btnZ);
        btnZ.setBounds(295, 322, 60, 53);

        btnS.setBackground(new java.awt.Color(0, 0, 0));
        btnS.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnS.setForeground(new java.awt.Color(255, 255, 255));
        btnS.setText("S");
        btnS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        jPanel1.add(btnS);
        btnS.setBounds(383, 322, 60, 53);

        btnG.setBackground(new java.awt.Color(0, 0, 0));
        btnG.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnG.setForeground(new java.awt.Color(255, 255, 255));
        btnG.setText("g");
        btnG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        jPanel1.add(btnG);
        btnG.setBounds(117, 389, 60, 53);

        btnU.setBackground(new java.awt.Color(0, 0, 0));
        btnU.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnU.setForeground(new java.awt.Color(255, 255, 255));
        btnU.setText("u");
        btnU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        jPanel1.add(btnU);
        btnU.setBounds(204, 389, 60, 53);

        btnO.setBackground(new java.awt.Color(0, 0, 0));
        btnO.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnO.setForeground(new java.awt.Color(255, 255, 255));
        btnO.setText("O");
        btnO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        jPanel1.add(btnO);
        btnO.setBounds(295, 389, 60, 53);

        btnJ.setBackground(new java.awt.Color(0, 0, 0));
        btnJ.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnJ.setForeground(new java.awt.Color(255, 255, 255));
        btnJ.setText("j");
        btnJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });
        jPanel1.add(btnJ);
        btnJ.setBounds(383, 389, 60, 53);

        btnR.setBackground(new java.awt.Color(0, 0, 0));
        btnR.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        btnR.setForeground(new java.awt.Color(255, 255, 255));
        btnR.setText("R");
        btnR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });
        jPanel1.add(btnR);
        btnR.setBounds(474, 389, 60, 53);

        item3.setEditable(false);
        item3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(item3);
        item3.setBounds(300, 200, 60, 49);

        item1.setEditable(false);
        item1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jPanel1.add(item1);
        item1.setBounds(120, 200, 60, 49);

        item2.setEditable(false);
        item2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });
        jPanel1.add(item2);
        item2.setBounds(210, 200, 60, 49);

        item4.setEditable(false);
        item4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ActionPerformed(evt);
            }
        });
        jPanel1.add(item4);
        item4.setBounds(390, 200, 60, 49);

        item5.setEditable(false);
        item5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        item5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(item5);
        item5.setBounds(470, 200, 60, 49);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/icons8_Idea_48px.png"))); // NOI18N
        jLabel3.setText("GUESS THE CORRCT WORD");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 10, 400, 60);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Image/icons8_Home_52px.png"))); // NOI18N
        jButton12.setText("MAIN MENU");
        jButton12.setToolTipText("click to go back to Game Main Menu");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(10, 10, 130, 70);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LEVEL 2");
        jLabel4.setToolTipText("Level 1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(630, 330, 110, 40);

        question.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("Opposite of Tall");
        question.setToolTipText("question");
        jPanel1.add(question);
        question.setBounds(180, 100, 280, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nextbtnStateChanged
        // TODO add your handling code here:
        //        isComplete1();
        //        if(isComplete1() == true){
            //            jButton1.setEnabled(true);
            //        }
    }//GEN-LAST:event_nextbtnStateChanged

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        // TODO add your handling code here:
        Level3 lvl3 = new Level3();
        dispose();
    }//GEN-LAST:event_nextbtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Do you wany to exit the Game?");
        if(res == JOptionPane.YES_OPTION) {
            System.exit(0);

            if(res == JOptionPane.NO_OPTION) {
                return;
            }

        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
            JOptionPane.INFORMATION_MESSAGE);
        
        item5.setText("T");
        btnT.setText("");
        if(btnT.getText() ==""){
            btnT.setEnabled(false);
        }

        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();

        answer();
    }//GEN-LAST:event_btnTActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
            JOptionPane.INFORMATION_MESSAGE);

        item2.setText("H");
        btnH.setText("");
        if(btnH.getText() ==""){
            btnH.setEnabled(false);
        }
        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();

        answer();
    }//GEN-LAST:event_btnHActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
            JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnNActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
            JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnZActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
            JOptionPane.INFORMATION_MESSAGE);

        item1.setText("S");
        btnS.setText("");
        if(btnS.getText() ==""){
            btnS.setEnabled(false);

        }
        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();

        answer();
    }//GEN-LAST:event_btnSActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
            JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnGActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
            JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnUActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
            JOptionPane.INFORMATION_MESSAGE);

        
        item3.setText("O");
        btnO.setText("");
        if(btnO.getText() ==""){
            btnO.setEnabled(false);
        }
        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();

        answer();
    }//GEN-LAST:event_btnOActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You guessed the wrong word", "wrong guess",
            JOptionPane.ERROR_MESSAGE);
        return;
    }//GEN-LAST:event_btnJActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Correct guess", "prompt",
            JOptionPane.INFORMATION_MESSAGE);

        item4.setText("R");
        
        btnR.setText("");
        if(btnR.getText() ==""){
            btnR.setEnabled(false);
        }
        
        val1  = btnH.getText();
        val2 = btnO.getText();
        val3 = btnO.getText();
        val4 = btnT.getText();
        val5 = btnS.getText();

        answer();
    }//GEN-LAST:event_btnRActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_item2ActionPerformed

    private void item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_item4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "the game is still ongoing\nDo you wany to return to the main menu?");
        if(res == JOptionPane.YES_OPTION) {
            HomePage home = new HomePage();
            dispose();

            if(res == JOptionPane.NO_OPTION) {
                return;
            }

        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         xOffset = evt.getX();
         yOffset = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
         int Kox = evt.getXOnScreen();
           int koy = evt.getYOnScreen();
           
           this.setLocation(Kox - xOffset, koy - yOffset);
           
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnZ;
    private javax.swing.JTextField item1;
    private javax.swing.JTextField item2;
    private javax.swing.JTextField item3;
    private javax.swing.JTextField item4;
    private javax.swing.JTextField item5;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextbtn;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
